name: Run gradle build task

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run unit tests
        run: ./gradlew clean build